### O sqlite3
- https://docs.python.org/3/library/sqlite3.html
- Vamos tratar uma base fictícia de alunos da Hashtag
- A base já está disponível em:
    - BaseDados.db
    - https://drive.google.com/file/d/12myCVaqez4kE-ZkCtHQjfDK7MDOxbmTj/view?usp=sharing

In [ ]:
import sqlite3
con = sqlite3.connect("BaseDados.db")

In [ ]:
cur = con.cursor()

In [ ]:
cur.execute('SELECT * FROM dados')

resultado = cur.fetchall()

In [76]:
cur.description

(('index', None, None, None, None, None, None),
 ('id_aluno', None, None, None, None, None, None),
 ('nome_aluno', None, None, None, None, None, None),
 ('cod_matricula', None, None, None, None, None, None),
 ('e-mail', None, None, None, None, None, None),
 ('acesso_plataforma', None, None, None, None, None, None),
 ('acesso_liberado', None, None, None, None, None, None),
 ('dias_ultimo_acesso', None, None, None, None, None, None),
 ('nr_prova', None, None, None, None, None, None),
 ('prova_feita', None, None, None, None, None, None),
 ('nota_prova', None, None, None, None, None, None))

In [77]:
colunas = []
    
for i in cur.description:
    colunas.append(i[0])

colunas

['index',
 'id_aluno',
 'nome_aluno',
 'cod_matricula',
 'e-mail',
 'acesso_plataforma',
 'acesso_liberado',
 'dias_ultimo_acesso',
 'nr_prova',
 'prova_feita',
 'nota_prova']

In [78]:
colunas2 = [
    i[0] for i in cur.description
]

colunas2

['index',
 'id_aluno',
 'nome_aluno',
 'cod_matricula',
 'e-mail',
 'acesso_plataforma',
 'acesso_liberado',
 'dias_ultimo_acesso',
 'nr_prova',
 'prova_feita',
 'nota_prova']

In [79]:
# Salvando em um DataFrame do pandas
import pandas as pd

resultado = pd.DataFrame(resultado)

resultado.columns =  [
    i[0] for i in cur.description
]

resultado.head()

,index,id_aluno,nome_aluno,cod_matricula,e-mail,acesso_plataforma,acesso_liberado,dias_ultimo_acesso,nr_prova,prova_feita,nota_prova
0,0,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,1,1,9.0
1,1,2,Bárbara da Cunha,63546,barbara@hashtag.com,0,1,2,1,1,10.0
2,2,3,Kevin Melo,80515,kevin@hashtag.com,1,1,3,1,1,7.0
3,3,4,Pedro Henrique da Costa,68004,pedro@hashtag.com,1,1,1,1,1,4.0
4,4,5,Mirella Viana,28421,mirella@hashtag.com,1,1,1,1,1,7.0

In [80]:
resultado.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               43 non-null     int64
 1   id_aluno            43 non-null     int64
 2   nome_aluno          43 non-null     str
 3   cod_matricula       43 non-null     int64
 4   e-mail              43 non-null     str
 5   acesso_plataforma   43 non-null     int64
 6   acesso_liberado     43 non-null     int64
 7   dias_ultimo_acesso  43 non-null     int64
 8   nr_prova            43 non-null     int64
 9   prova_feita         43 non-null     int64
 10  nota_prova          24 non-null     float64
dtypes: float64(1), int64(8), str(2)
memory usage: 3.8 KB

In [81]:
resultado.shape

(43, 11)

In [82]:
coluna =  [i[0] for i in cur.description]

In [83]:
cur.execute('SELECT * FROM dados')
resultado = cur.fetchall()
resultado = pd.DataFrame(resultado)
resultado.columns = coluna
resultado.head()

,index,id_aluno,nome_aluno,cod_matricula,e-mail,acesso_plataforma,acesso_liberado,dias_ultimo_acesso,nr_prova,prova_feita,nota_prova
0,0,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,1,1,9.0
1,1,2,Bárbara da Cunha,63546,barbara@hashtag.com,0,1,2,1,1,10.0
2,2,3,Kevin Melo,80515,kevin@hashtag.com,1,1,3,1,1,7.0
3,3,4,Pedro Henrique da Costa,68004,pedro@hashtag.com,1,1,1,1,1,4.0
4,4,5,Mirella Viana,28421,mirella@hashtag.com,1,1,1,1,1,7.0

In [84]:
comando = 'SELECT nome_aluno, cod_matricula FROM dados'
cur.execute(comando)
resultado = cur.fetchall()
resultado = pd.DataFrame(resultado)
resultado.columns = [i[0] for i in cur.description]
resultado.head()

                nome_aluno  cod_matricula
0   Maria Eduarda da Rocha          38273
1         Bárbara da Cunha          63546
2               Kevin Melo          80515
3  Pedro Henrique da Costa          68004
4            Mirella Viana          28421

In [85]:
# Função para consultar dados

def executa_sql(comando):
    cur.execute(comando)
    resultado = cur.fetchall()
    resultado = pd.DataFrame(resultado)
    resultado.columns = [i[0] for i in cur.description]
    print(resultado.shape)
    #display(resultado.head())

    return resultado

In [86]:
executa_sql('SELECT nome_aluno, [e-mail] as email FROM dados')

(43, 2)

                 nome_aluno                 email
0    Maria Eduarda da Rocha     maria@hashtag.com
1          Bárbara da Cunha   barbara@hashtag.com
2                Kevin Melo     kevin@hashtag.com
3   Pedro Henrique da Costa     pedro@hashtag.com
4             Mirella Viana   mirella@hashtag.com
5               Lívia Jesus     lívia@hashtag.com
6                Lara Lopes      lara@hashtag.com
7             Lucca Cardoso     lucca@hashtag.com
8            Isabelly Souza  isabelly@hashtag.com
9                Cauã Porto      cauã@hashtag.com
10           Maria Ferreira     maria@hashtag.com
11              Júlia Pinto     julia@hashtag.com
12          Antônio Azevedo  lovedogs@hashtag.com
13               Laura Melo     laura@hashtag.com
14         Gabriela Costela  gabriela@hashtag.com
15             Eloah Aragão     eloah@hashtag.com
16          Francisco Pires      x!c0@hashtag.com
17          Bárbara Freitas   barbara@hashtag.com
18          Melissa Ribeiro   melissa@hashtag.com
19         Lavínia Carvalho   lavinia@hashtag.com
20   Maria Eduarda da Rocha     maria@hashtag.com
21         Bárbara da Cunha   barbara@hashtag.com
22               Kevin Melo     kevin@hashtag.com
23            Mirella Viana   mirella@hashtag.com
24              Lívia Jesus     lívia@hashtag.com
25           Isabelly Souza  isabelly@hashtag.com
26           Maria Ferreira     maria@hashtag.com
27              Júlia Pinto     julia@hashtag.com
28          Antônio Azevedo  lovedogs@hashtag.com
29               Laura Melo     laura@hashtag.com
30         Gabriela Costela  gabriela@hashtag.com
31             Eloah Aragão     eloah@hashtag.com
32          Bárbara Freitas   barbara@hashtag.com
33          Melissa Ribeiro   melissa@hashtag.com
34   Maria Eduarda da Rocha     maria@hashtag.com
35           Maria Ferreira     maria@hashtag.com
36              Júlia Pinto     julia@hashtag.com
37             Eloah Aragão     eloah@hashtag.com
38          Bárbara Freitas   barbara@hashtag.com
39          Melissa Ribeiro   melissa@hashtag.com
40   Maria Eduarda da Rocha     maria@hashtag.com
41             Eloah Aragão     eloah@hashtag.com
42             Eloah Aragão     eloah@hashtag.com

In [87]:
resultado.tail()

                nome_aluno  cod_matricula
38         Bárbara Freitas          19442
39         Melissa Ribeiro          38438
40  Maria Eduarda da Rocha          38273
41            Eloah Aragão          65749
42            Eloah Aragão          65749

In [88]:
resultado.drop_duplicates()

                 nome_aluno  cod_matricula
0    Maria Eduarda da Rocha          38273
1          Bárbara da Cunha          63546
2                Kevin Melo          80515
3   Pedro Henrique da Costa          68004
4             Mirella Viana          28421
5               Lívia Jesus          22284
6                Lara Lopes          38362
7             Lucca Cardoso          45109
8            Isabelly Souza          31859
9                Cauã Porto          42674
10           Maria Ferreira          86563
11              Júlia Pinto          47086
12          Antônio Azevedo          29022
13               Laura Melo          50966
14         Gabriela Costela          21262
15             Eloah Aragão          65749
16          Francisco Pires          59518
17          Bárbara Freitas          19442
18          Melissa Ribeiro          38438
19         Lavínia Carvalho          89428

In [90]:
executa_sql('SELECT DISTINCT nome_aluno, cod_matricula FROM dados')

(20, 2)

                 nome_aluno  cod_matricula
0    Maria Eduarda da Rocha          38273
1          Bárbara da Cunha          63546
2                Kevin Melo          80515
3   Pedro Henrique da Costa          68004
4             Mirella Viana          28421
5               Lívia Jesus          22284
6                Lara Lopes          38362
7             Lucca Cardoso          45109
8            Isabelly Souza          31859
9                Cauã Porto          42674
10           Maria Ferreira          86563
11              Júlia Pinto          47086
12          Antônio Azevedo          29022
13               Laura Melo          50966
14         Gabriela Costela          21262
15             Eloah Aragão          65749
16          Francisco Pires          59518
17          Bárbara Freitas          19442
18          Melissa Ribeiro          38438
19         Lavínia Carvalho          89428