In [1]:
# Criando a conexão
import sqlite3
con = sqlite3.connect("BaseDados.db")

In [2]:
# Criando um cursos
cur = con.cursor()

In [3]:
# Buscando todas as informações da tabela
cur.execute('SELECT * FROM dados')

resultado = cur.fetchall()

In [4]:
import pandas as pd

resultado = pd.DataFrame(resultado)

resultado.columns =  [
    i[0] for i in cur.description
]

resultado.head()

,index,id_aluno,nome_aluno,cod_matricula,e-mail,acesso_plataforma,acesso_liberado,dias_ultimo_acesso,nr_prova,prova_feita,nota_prova
0,0,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,1,1,9.0
1,1,2,Bárbara da Cunha,63546,barbara@hashtag.com,0,1,2,1,1,10.0
2,2,3,Kevin Melo,80515,kevin@hashtag.com,1,1,3,1,1,7.0
3,3,4,Pedro Henrique da Costa,68004,pedro@hashtag.com,1,1,1,1,1,4.0
4,4,5,Mirella Viana,28421,mirella@hashtag.com,1,1,1,1,1,7.0

In [5]:
# Função para consultar dados

def executa_sql(comando):
    cur.execute(comando)
    resultado = cur.fetchall()
    resultado = pd.DataFrame(resultado)
    resultado.columns = [i[0] for i in cur.description]
    print(resultado.shape)
    #display(resultado.head())

    return resultado

In [16]:
executa_sql('SELECT MIN(dias_ultimo_acesso) as Minimo, \
            MAX(dias_ultimo_acesso) as Máximo, \
            AVG(dias_ultimo_acesso) as Média FROM dados')

(1, 3)

   Minimo  Máximo     Média
0       1      14  5.116279

In [22]:
executa_sql('SELECT nome_aluno, COUNT(id_aluno) FROM dados GROUP BY nome_aluno')

(20, 2)

                 nome_aluno  COUNT(id_aluno)
0           Antônio Azevedo                2
1           Bárbara Freitas                3
2          Bárbara da Cunha                2
3                Cauã Porto                1
4              Eloah Aragão                5
5           Francisco Pires                1
6          Gabriela Costela                2
7            Isabelly Souza                2
8               Júlia Pinto                3
9                Kevin Melo                2
10               Lara Lopes                1
11               Laura Melo                2
12         Lavínia Carvalho                1
13            Lucca Cardoso                1
14              Lívia Jesus                2
15   Maria Eduarda da Rocha                4
16           Maria Ferreira                3
17          Melissa Ribeiro                3
18            Mirella Viana                2
19  Pedro Henrique da Costa                1

In [34]:
executa_sql('SELECT  nome_aluno, AVG(id_aluno) as Média FROM dados WHERE nota_prova is not null GROUP BY nome_aluno')

(15, 2)

                 nome_aluno  Média
0           Antônio Azevedo   13.0
1           Bárbara Freitas   18.0
2          Bárbara da Cunha    2.0
3              Eloah Aragão   16.0
4          Gabriela Costela   15.0
5            Isabelly Souza    9.0
6               Júlia Pinto   12.0
7                Kevin Melo    3.0
8                Laura Melo   14.0
9               Lívia Jesus    6.0
10   Maria Eduarda da Rocha    1.0
11           Maria Ferreira   11.0
12          Melissa Ribeiro   19.0
13            Mirella Viana    5.0
14  Pedro Henrique da Costa    4.0

In [33]:
executa_sql('SELECT nome_aluno, AVG(id_aluno) as Média FROM dados \
            WHERE nota_prova is not null \
            GROUP BY nome_aluno \
            ORDER BY AVG(id_aluno) desc')

(15, 2)

                 nome_aluno  Média
0           Melissa Ribeiro   19.0
1           Bárbara Freitas   18.0
2              Eloah Aragão   16.0
3          Gabriela Costela   15.0
4                Laura Melo   14.0
5           Antônio Azevedo   13.0
6               Júlia Pinto   12.0
7            Maria Ferreira   11.0
8            Isabelly Souza    9.0
9               Lívia Jesus    6.0
10            Mirella Viana    5.0
11  Pedro Henrique da Costa    4.0
12               Kevin Melo    3.0
13         Bárbara da Cunha    2.0
14   Maria Eduarda da Rocha    1.0